manifest:
  remotes:
    - name: bsalex
      url-base: https://github.com/bsalex
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-behavior-dynamic-macros
      remote: bsalex
      # This points to a west manifest file in the remote module for further imports
      import: west.yml
